site_name: RustSmith Documentation
copyright: Copyright &copy; 2023 Mayank Sharma
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/rustsmith

theme:
  name: material
  icon:
    logo: material/language-rust
  palette:
    - scheme: default
      primary: white
      secondary: black
      toggle:
          icon: material/weather-sunny
          name: Switch to dark mode
    - scheme: slate
      primary: black
      secondary: white
      toggle:
        icon: material/weather-night
        name: Switch to light mode
  features:
    - navigation.instant
    - navigation.top
    - navigation.path
    - navigation.indexes
    - navigation.footer
    - search.suggest
    - search.share
    - search.highlight

plugins:
  - search

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences


